version: '4'

services:
  db:
    container_name: postgresdb
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: books
    image: postgres:alpine3.19
  
  app:
    container_name: booksapi
    depends_on:
      - db
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: postgresql://postgres:password123@postgresdb:5432/books
      PORT: 3000
    build: .


volumes:
  postgres-volume:
    external: false